[package]
name = "clean_code"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.5"
chrono = "0.4"
rust_decimal = "1.14"
rust_decimal_macros = "1.14"
