/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIFoo */

#ifndef _Included_JNIFoo
#define _Included_JNIFoo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIFoo
 * Method:    nativeFoo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIFoo_nativeFoo
  (JNIEnv *, jobject);

/*
 * Class:     JNIFoo
 * Method:    f
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_JNIFoo_f
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
